### ISSUE TITLE
Why does loading a deck(s) erases old decks?

### ISSUE THREAD

**Issue by brunobord** [abeleinin/goki#9]
I've noticed that after a relaunch of goki, the card decks were simply deleted. 

I'm not a Go dev, but I think that the following code is responsible of that: https://github.com/abeleinin/goki/blob/main/util.go#L122-L130

Why does `goki` behaves like this? What's the point in erasing the old decks (and when they're erased, it triggers an error because the data contained in the `~/.local/share/goki/decks.json` is not cleaned up, and it refers to a non existing deck, to it crashes).

Do you have any idea of what's going on and what _should_ rather happen?

**Comment by abeleinin** [comment]
In retrospect, the whole file storage system is really poorly thought out and needs a refactor. With finals and other projects, I haven't spent much time thinking about this project, but I'll have time over the weekend to fix this.

The reason for the deletion is due to the deck naming convention using the `{deck name}_{uuid}.json`. If the user renames a deck then the filename also needs to be updated. Static deck file names could be an obvious solution here, not sure why I didn't just do that in the first place lol.

Also, it's occurring to me that all the deck data is simply loaded into the Go data structures and deletes the only "backup". So, if the program crashes or you quit in an unexpected way (not using a programmed quit option), such that the [saveAll()](https://github.com/abeleinin/goki/blob/main/util.go#L71) function isn't called, your data is lost.

Thank you for pointing this out, and sorry if you lost any data. Let me know if you have any suggestions or thoughts.

**Comment by abeleinin** [comment]
I just pushed an update to improve the card loading/saving logic. It removes the weird deck deletion on load and should more reliably save card data. Let me know if you have any other issues!
